### ISSUE TITLE
Issues with beta8 and ASP.NET 5 (vNext) - MVC sample with OpenID Connect

### ISSUE THREAD

**Issue by drewid** [auth0/auth0-aspnet-owin#17]
Hello,

I am getting errors running the examples as it seems the to have problems beta8 (or sometime before, not sure when the breaking changes happened).  There are issues with Account Controller and project.json and the dependencies.

Does not seem to exist anymore:
Microsoft.AspNet.Http.Security 

I am getting the following error with the following dependencies "the dependency does not support the framework DNX (for both versions 4.5.1 and 4.6) and DNX Core.

Microsoft.AspNet.Security
Microsoft.AspNet.Security.Cookies
Microsoft.AspNet.Security.OpenIdConnect

Because of this it can't resolve the following:
Context.User
Conext.Response
OpenIdConnectAuthenticationResults
middlewareOptions.Options
CookieAuthenticationDefaults

I'd really like to use this setsup with Auth0 and ASP.NET 5.  Any help on deciphering this would be greatly appreciated.

Thanks!

**Comment by sandrinodimattia** [comment]
Hi @drewid, sorry for the confusion but our ASP.NET 5 support is in a different repository where we have samples: https://github.com/auth0/auth0-aspnet5

**Comment by drewid** [comment]
Fantastic.  Thanks for the info, a big help and making a lot more sense!!!
