### ISSUE TITLE
Update the ASP.NET 5 example to RC1-Final

### ISSUE THREAD

**Issue by sirkirby** [auth0/auth0-aspnet-owin#20]
Hello, I submitted an issue last week here: https://github.com/auth0/auth0-aspnet5/issues/4 trying to get some info on RC1 compatibility.  Can you please let me know if this is something you plan to do? Thanks!

**Comment by sandrinodimattia** [comment]
Hi there, our samples have been updated to RC1: https://github.com/auth0/auth0-aspnet5
