### ISSUE TITLE
Remove dependency on System.Web

### ISSUE THREAD

**Issue by arieradle** [auth0/auth0-aspnet-owin#37]
The handler contains dependency on System.Web due to a single line of code:

Line 279 in Auth0AuthenticationHandler.cs:
`var state = HttpUtility.ParseQueryString(context.Request.Query["state"]);`

I think it's possible to use Uri.ParseQueryString

This dependency is redundant, and while it's in place, I'm not sure if this middleware can be used in selfhosting scenarios

**Comment by itsho** [comment]
I'm need the exact same thing.

**Comment by jerriep** [comment]
I will look into your issues sometimes next week @arieradle
