### ISSUE TITLE
basic-mvc-sample

### ISSUE THREAD

**Issue by Amialc** [auth0/auth0-aspnet-owin#39]
Logout works with only global logoutURL
![image](https://cloud.githubusercontent.com/assets/1114365/15449530/162c3142-1f89-11e6-8ee8-e6d21aee28e7.png)
![image](https://cloud.githubusercontent.com/assets/1114365/15449529/090a589a-1f89-11e6-8f1d-135650d2138d.png)

![image](https://cloud.githubusercontent.com/assets/1114365/15449535/2af5ce1c-1f89-11e6-87a4-ada04238b18b.png)

**Comment by BrianVallelunga** [comment]
I ran in to this issue too. Try including the client_id in the call to /v2/logout. Then it will use the client app-specific logout urls.

**Comment by jerriep** [comment]
The middleware has been updated since to support handling logout correctly, and passing the client id. 

See OWIN Quickstart for more info for how to implement:
https://auth0.com/docs/quickstart/webapp/aspnet-owin/01-login
