### ISSUE TITLE
State not passed to callback

### ISSUE THREAD

**Issue by BrianVallelunga** [auth0/auth0-aspnet-owin#43]
In a SSO scenario, I redirect my users to https://myapp.auth0.com/authorize?state=HelloWorld&redirect_uri=https://myapp/signin-auth0....

When a user authenticates they get redirected to the /signin-auto0 middleware, which in turn sends them to my custom callback, /auth0/callback

Unfortunately, the state value seems to be lost when it gets to my callback. Is this a result of the commented out line at:

https://github.com/auth0/auth0-aspnet-owin/blob/master/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L298

Without this, I can't send the users to the page that they want to go.

**Comment by jerriep** [comment]
@BrianVallelunga This is a very old issue. Is this still relevant?

**Comment by jerriep** [comment]
Closing this issue. Feel free to re-open if this is still an issue
