### ISSUE TITLE
Errors not Displayed by ExternalLoginCallback

### ISSUE THREAD

**Issue by adamreed90** [auth0/auth0-aspnet-owin#44]
When enabling for example, the rule for Forcing EMail Verification, the default Auth0AccountController.cs does not parse the Error/Error_Description sent to it by Auth0.

A simple update allows the error message to be displayed:

        [AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl, string error, string error_description)
        {
            if (!string.IsNullOrEmpty(error))
            {
                return Content("ERROR: " + error_description);
            }
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);

            var externalIdentity = await AuthenticationManager.GetExternalIdentityAsync(DefaultAuthenticationTypes.ExternalCookie);
            if (externalIdentity == null)
            {
                throw new Exception("Could not get the external identity. Please check your Auth0 configuration settings and ensure that " +
                                    "you configured UseCookieAuthentication and UseExternalSignInCookie in the OWIN Startup class. " +
                                    "Also make sure you are not calling setting the callbackOnLocationHash option on the JavaScript login widget.");
            }

            AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = false }, CreateIdentity(externalIdentity));
            return RedirectToLocal(returnUrl);
        }

**Comment by jerriep** [comment]
@adamreed90 

We are no longer including the `Auth0AccountController` class. You can handle this very easily yourself by setting the `ErrorRedirectPath` of `Auth0AuthenticationOptions`, e.g. `ErrorRedirectPath = new PathString("/Home/Error")`.

Then create a controller action which handles that route, and extract the `error` and `error_description` querystring values to display a proper authentication failed message to the user.
