### ISSUE TITLE
Federated logout not supported

### ISSUE THREAD

**Issue by MoppDepp** [auth0/auth0-aspnet-owin#47]
How one should implement federated logout in v2.0?
https://github.com/auth0/auth0-aspnet-owin/blob/master/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L224

**Comment by jerriep** [comment]
@MoppDepp I'll look into adding this

**Comment by jerriep** [comment]
I see you opened a Zendesk issue as well

Let's close this and rather carry on on Zendesk

**Comment by jerriep** [comment]
Support added in 2.1.0 (https://www.nuget.org/packages/Auth0-ASPNET-Owin)

Add `.federated` dictionary key with value of `true` to `AuthenticationProperties` when logging out:

```
public void Logout()
{
    HttpContext.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);
    HttpContext.GetOwinContext()
        .Authentication.SignOut(new AuthenticationProperties(
            new Dictionary<string, string>
            {
                {".federated", "true"}
            })
        {
            RedirectUri = Url.Action("Index", "Home"),
        }, "Auth0");
}
```
