### ISSUE TITLE
Auth0AuthenticatedContext ClaimsIdentity missing Email claim

### ISSUE THREAD

**Issue by sghobbs** [auth0/auth0-aspnet-owin#55]
**Current Behavior**:
As intended, the user passes through an Auth0 authentication flow, returning a normalized JSON identity profile, which the `Auth0AuthenticationProvider` middleware then transforms to a strongly-typed `ClaimsIdentity`. This `ClaimsIdentity` is available via the `Auth0AuthenticatedContext` instance passed to the OnAuthenticated event callback, and it is also automatically set as the thread `Identity` by the time the Auth0 OWIN middleware completes its thing.

**However**, it appears that the Email property is never properly set to this identity, so it's unavailable to the application. The `Auth0AuthenticatedContext.Email` property is always null, and the `ClaimsIdentity` has no email claim. This is particularly problematic, since the email claim is usually the key unique identifier for a principal.

**Note**: It is also possible that other claims are not being set. There seem to be more claims in the raw JSON result than what end up in the `ClaimsIdentity`.

**Expected Behavior**:
The Auth0AuthenticatedContext.Email property should properly contain the string provided in the .email JSON property of the normalized profile. Additionally, the `ClaimsIdentity` generated by the middleware should have an Email claim (_http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress_) with this value.

Thanks!

**Comment by sghobbs** [comment]
**Update**: It seems I am able to replicate this issue only when using the hosted Auth0 login page, in which instance the JSON profile seems to lack an email property (regardless of which connection I try). **This may then be just an issue with my client configuration, rather than the library.** I apologize.

(When I authenticate the user via the auth0-lock.js library hosted on my own site, the email claim is being provided as expected.)

**Comment by aaguiarz** [comment]
Are you asking for the 'email' scope in the .net app?

**Comment by sghobbs** [comment]
@aaguiarz That's it. I wasn't asking for the "email" scope when registering the Auth0AuthenticationOptions. (I was, however, asking for the email scope in my auth0-lock.js instance, which is why it worked there.) Adding the "email" scope in my startup.cs resolves this issue.

It would be helpful to add a step for adding the "email" scope to the [Getting the Profile](https://auth0.com/docs/quickstart/webapp/aspnet-owin/03-user-profile) section of the OWIN quickstart. (I'm kind of new to Auth0, and I know a lot changed recently for OIDC compliance. Was the email once included in the default scope?)

Thank you!

**Comment by jerriep** [comment]
Thank you for pointing this out @sghobbs and apologies for the confusion.

I have created PR auth0/docs#5555 to resolve this issue
