### ISSUE TITLE
Add caching mechanism for JWKS endpoints.

### ISSUE THREAD

**Issue by saltukalakus** [auth0/auth0-aspnet-owin#57]
It looks like, we don't provide a caching mechanism similar to [node-jwks-rsa](https://github.com/auth0/node-jwks-rsa#caching) library. Can we add this support? ZD # 35507

**Comment by jerriep** [comment]
The `ConfigurationManager` class we use internally (https://github.com/auth0/auth0-aspnet-owin/blob/b99a998389e772c9b10338bcd01539f5f520961a/src/Auth0.Owin.OpenIdConnectSigningKeyResolver/OpenIdConnectSigningKeyResolver.cs#L16) caches the keys. I tested it at the time by also monitoring network traffic, so I believe this is indeed the case.

Do you have experience of the contrary? If so then I'll investigate further.

**Comment by saltukalakus** [comment]
Hi Jerrie, 

I haven't tested. To be honest I'm novice for .net . Could you confirm if my understanding is correct;

Once I create the object;

```
var keyResolver = new OpenIdConnectSigningKeyResolver("https://your_tenant.auth0.com");
```

I expect, consecutive calls to getting signing key will trigger at some point a request to JWKS endpoint to refresh the public keys.

```
keyResolver.GetSigningKey(identifier)
```

I've two questions in that case;

1- What is the default cache period and can I configure timeout period?
2- During cache refresh, what happens if a network failure happens? Can the previously cached keys be still used? In ZD # 35507 , I guess, we are having issue once network call is failing for refresh request.

**Comment by jerriep** [comment]
Yes, your understanding is correct. I am not sure internally when the `ConfigurationManager` class download the keys from the JWKS endpoint - whether on instantiation, or the first time it needs it. Either case, it will make that call once and then cache the keys.

1. I believe 24 hours, but not sure. Also not sure whether we can override that. I need to look into it, as that source code is from internal MS libraries.

2. Once again, since that source code is from a MS library, I am not sure what happens. I need to investigate deeper. 

Also note that since I am not an Auth0 employee anymore, I do not have access to ZD ticket information. Feel free to share what you can regarding that ticket here.

**Comment by saltukalakus** [comment]
I asked the customer to join this conversation. Hopefully he can provide more details, such as how they use the library in their application etc.

Issue is something like this; I have compiled a few replies into one body. 

```
We are experiencing errors trying to access the information necessary to validate tokens: 
This the error I'm seeing: Unable to create to obtain configuration from: 
'https://customer-tenant.auth0.com/.well-known/openid-configuration'.

The problem temporarily goes away if I restart the server but then returns eventually.
```
Basically in our logs there isn't information for the root cause of the problem, and customer response;

```
My guess is that there wouldn't be an error in your log if the problem is that the ssl certificate wasn't
seen as being trusted/correct from the point of view of the Auth0 Owin library. While this error was
occurring, I also tried navigating in my browser to the endpoint and it was successful. So, presumably
the Auth0 Owin library code was able to get to the url, it just didn't trust the response so I don't think
this would cause an error on your servers since as far as they are concerned they served up the 
content successfully. During this same time period, the same server was hosting code that was 
accessing the customer-tenant.auth0.com configuration urls without a problem so I don't think 
it was a problem with our server.
```

**Comment by saltukalakus** [comment]
I can say that 2. item is more important. Configuring cache update time isn't critical. What could be a workaround in case there is an issue during request to endpoint? Following is the customer's proposal;
...
Maybe you can tell me if the following workaround is reasonable were this to happen again: 
I can host some of the configuration content on a server I have control over. 
So, take the content at: https://customer-tenant.auth0.com/.well-known/openid-configuration/ 
and https://customer-tenant.auth0.com/.well-known/jwks.json 
and put it on a server I have control over and has a public url that is working correctly. I would just need to change the "jwks_uri" property in the openid-configuration content to point to this new jwks.json url.

I tested it at the time and it worked. I'm assuming the jwks json content changes infrequently enough that this could serve as a temporary workaround should this problem happen again.

**Comment by jerriep** [comment]
My suggestion would be that the customer stores the actual public key which is used for validating the token on the server and then use that.

No 100% sure off-hand what this will look like. 

Let me work on a sample and get back to you

**Comment by jerriep** [comment]
@saltukalakus I created a sample which demonstrates how to use a certificate which is downloaded from Auth0. You can find this sample here:
https://github.com/auth0-samples/auth0-aspnet-owin-webapi-samples/tree/master/Samples/rs256-local-certificate

The readme file in the project folder describes what to do. It is pretty straightforward.

Let me know whether this solves your customer's issue

**Comment by brianhulick** [comment]
I'm the customer in question and I, more or less, use the example code here:
https://auth0.com/docs/quickstart/backend/webapi-owin/01-authorization

This snippet is from the OwinStartup class:

```
public class Startup
{
	public void Configuration(IAppBuilder app)
	{
		var keyResolver = new OpenIdConnectSigningKeyResolver("https://my-tenant.auth0.com/");
		app.UseJwtBearerAuthentication(
			new JwtBearerAuthenticationOptions
			{
				AuthenticationMode = AuthenticationMode.Active,
				TokenValidationParameters = new TokenValidationParameters()
				{
					ValidAudience = "my-api-identifier",
					ValidIssuer = "https://my-tenant.auth0.com/",
					IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) => keyResolver.GetSigningKey(identifier)
				}
			});
	}
}
```

Does this automatically leverage the library's internal caching?

**Comment by brianhulick** [comment]
@jerriep Thank you for that certificate example. That makes sense and is easier to work with than attempting to mimic the output of the openid-configuration endpoint. Do you know long is that certificate valid for? If I were to download the .cer file now and then not need it for a year or so, would it still be valid?

**Comment by jerriep** [comment]
> Does this automatically leverage the library's internal caching?

Yes it does

> Do you know long is that certificate valid for?

I am not an Auth0 employee anymore, so I do not really have easy access to the internal people to confirm this for you. **But**, from what I remember when I was still an employee, Auth0 does not cycle the certificates. But maybe @saltukalakus can confirm that for us?

**Comment by aaguiarz** [comment]
@brianhulick you'll need to assume that the JWKS could be invalid. 

You get it from the cache, try to validate the token, and if you get an error because the JWKS is not valid, the cache needs to be invalidated, and the JWKS downloaded again.

**Comment by jerriep** [comment]
@saltukalakus and @brianhulick I am closing this issue. Please feel free to comment or re-open if there are any more questions
