### ISSUE TITLE
This library should include Kentor.OwinCookieSaver by default

### ISSUE THREAD

**Issue by robertmclaws** [auth0/auth0-aspnet-owin#58]
Hey Jerrie,

In my experience with this library, any time you try to save an id_token or an access_token to an auth cookie, you hit the OWIN bug. It just bit me again at a state contract, and it took a little time to figure out. Why not just include the package in this project by default, and register it for the user inside the existing extension method? Then they get the correct behavior without the possibility of hitting authentication issues and trying to track them down?

Happy to open a PR if you're OK with it.

Thanks!

**Comment by jerriep** [comment]
Hi Robert,

We do make it clear in the Quickstart that users should use the Kentor library:
https://auth0.com/docs/quickstart/webapp/aspnet-owin/01-login

I do not think it is as simple as making it part of our library and handling the registration as part of our middleware, as the Kentor middleware appears to be very specific about where it must be registered. From their docs:

> Simply add it before any cookie handling middleware and it will preserve the authentication cookies.

So if we handle that, it means we should handle the registration of the cookie middleware as well, which may lead to lack of flexibility on our users' side.

@nicosabena You have much more experience with this. What do you think?

**Comment by robertmclaws** [comment]
So you're right, it IS in the QuickStart... but a) it's not mentioned in the NuGet package readme, and b) that assumes that every developer will go through the QuickStart. Most developer just download NuGet packages and then bang their head against their desk until they figure it out.

At one of my clients, I wrote a wrapper to help instantiate Auth0 the right way, without each developer having to learn the minute details of how it works. A partial screenshot is below: 
![image](https://user-images.githubusercontent.com/1657085/38373560-8ce6ede4-38bf-11e8-8828-043cef98b93d.png)

Theoretically, a constructor overload on `Auth0AuthenticationExtensions` that takes a `CookieAuthenticationOptions` parameter should do the trick. You could grab the `SetDefaultSignInAsAuthenticationType` from the `CookieAuthenticationOptions.AuthenticationType` value and be off to the races.

Thoughts?

**Comment by jerriep** [comment]
Hi Robert,

Yes, we can certainly make it clear in the package README as well. That is a big oversight on my part, and I will sort it out, thanks 👍 

As for a wrapper which does everything for the developer, I am very sceptical of doing that. It is unusual for a piece of authentication middleware to handle registration of the cookie middleware as well, so it is not something a developer will expect. So (1) this goes against the normal pattern for OWIN auth middleware, and (2) I am afraid this may cause more support issues down the line.

But that is why I pinged @nicosabena on this. Let's see whether he can also chip in, as he works with many ASP.NET customers (or at least, he used to in the past. Not sure if that is still the case)

**Comment by nicosabena** [comment]
Sorry, I missed the notifications.
I was the one adding the notes for the Kentor.OwinCookieSaver originally on the `readme.md` and later on the Quickstarts. Over the years, I think I must have answered about 10 issues related to this (which prompted me to update the quickstarts as well). 
We could definitely improve the package README to warn users about this. But I don't think it would be a good idea to add the package silently. As Jerrie says, this package requires being registered first, which is not feasible to do from our side. Also, the package is there to fix a bug in the OWIN pipeline, which might be corrected in a future release.

**Comment by jerriep** [comment]
Thank you @nicosabena. I will update the README which is displayed upon package installation accordingly to make it very clear that customers should install the Kentor lib, but for now, we will not provide a wrapper around this.

**Comment by nicosabena** [comment]
@robertmclaws What I meant is that in the extension method we can only control the order of things that happen within that method, but not the order in which users add other extensions as well.

I understand your point, and I'm not trying to be mean here, but doing too much in a library is a big risk. Taking a dependency on a third-party product that solves a problem that is tangential to what this library does just doesn't feel right in this case.

**Comment by robertmclaws** [comment]
@nicosabena I have to respectfully disagree with you here. Your first point is irrelevant because it's a truism that exists whether you act on this or not. Of course you can't "control" anything a developer does outside your library, *which is why libraries exist in the first place*... because it's a place you CAN control. 

Second, the problem is not tangential to your library at all. If you add more claims to your token in a rule, or populate both the ID_TOKEN and ACCESS_TOKEN when you call AuthenticationManager.SignIn(), then you cause the cookie to overflow past the size limits and be split into multiple cookies, and your library **DOESN'T WORK 100% of the time** without that package. It's like saying you need to use JSON, but not taking a dependency on Newtonsoft.Json. It doesn't make any sense.

You CAN absolutely control whether or not the end user is successful here. You're just choosing not to for the sake of following some arbitrary pattern. When Auth0 started, no one put pastable code with customer configuration into sample docs. Auth0 exists and is successful because the company bucked established patterns to *do better*, and I'm pretty sure @eugeniop would agree with me on that point.

**Comment by jerriep** [comment]
@robertmclaws Look, what you are proposing is not how any other piece of OWIN auth middleware works. Also, it is hiding implementation details from developers and can cause more support issues down the line - support issues which we will have to attend to, not you.

The underlying issue with the cookies is in the OWIN middleware, not ours. And the solution is known. I will update the readme which gets shown after installation to make it more clear to developers that they need to take care to install the Kentor library, but that is as far as I will go.
