### ISSUE TITLE
This implementation has a big problem when cancelling the oauth flow

### ISSUE THREAD

**Issue by bipa** [auth0/auth0-aspnet-owin#6]
Do the following:

1) Login with facebook

2) logout

3) Try login again with linkedin, but CANCEL the grant flow

4) You are then authenticated with facebook still......

For me it looks like the signout is not clearing the cookie...

We are using this solution, so it would be great if this issue was fixed....

**Comment by jerriep** [comment]
No movement on this issue in a very long time. Please reopen issue if it is still relevant.
