### ISSUE TITLE
OWIN 4 support

### ISSUE THREAD

**Issue by VyacheslavPritykin** [auth0/auth0-aspnet-owin#60]
Is there any ETA to support OWIN 4?

**Comment by jerriep** [comment]
Currently, there is no way around the incompatibilities I laid out over here:
https://community.auth0.com/t/webapi-owin-example-is-not-working/9704/2

**Comment by VyacheslavPritykin** [comment]
@jerriep Does it mean that with OWIN 4 it's impossible to validate issued JWT tokens? It sounds weird.
In you comment you wrote: 

> One definite dependency issue I cannot appear to work around is that the System.IdentityModel.Tokens.Jwt 5.x library does not work with non-ASP.NET Core projects. You can also see this discussed over here:
https://github.com/IdentityServer/IdentityServer3/issues/3017

However, the mentioned issue in IdentityServer3 was caused by the fact that the System.IdentityModel.Tokens.Jwt v5 was incompatible with OWIN 3. It's not the case for now, since it can work with OWIN 4.

**Comment by jerriep** [comment]
@VyacheslavPritykin 

Let's maybe start off with establishing *what* it is you want to use in OWIN 4. This repo contains source for multiple NuGet packages. Which one is it *exactly* you are trying to use with OWIN 4?

**Comment by VyacheslavPritykin** [comment]
@jerriep I'm interested in Auth0.Owin.OpenIdConnectSigningKeyResolver.
I want to update OWIN to v4 in one project and it seems that after that the customers won't be able to use Auth0 access tokens as authorization tokens for this project.

**Comment by jerriep** [comment]
I tried to get `OpenIdConnectSigningKeyResolver` working on OWIN 4 a month or so ago and was unable to do so. I ran into multiple runtime issues - not just the ones listed.

I plan to look at it again, but it is unlikely it will happen in the next month. If you need this urgently you are welcome to look into it yourself, and, if you can get it working, submit a PR.

**Comment by jerriep** [comment]
I can give no guarantees that it will support OWIN 4, due to my previous problems with getting it working. But, I will give it another go to see whether I can make everything working together.

Will keep you updated.

**Comment by lukelengl** [comment]
I was able to get OWIN 4 to work without using `OpenIdConnectSigningKeyResolver`.

I have the following NuGet packages:
Microsoft.Owin.Host.SystemWeb 4.0.0
Microsoft.IdentityModel.Protocols.OpenIdConnect 5.2.2
Microsoft.IdentityModel.Tokens 5.2.2
Microsoft.Owin.Security.Jwt 4.0.0

Then I can just use the following: (Here's my modifications to Auth0 Quickstart guide found here: https://auth0.com/docs/quickstart/backend/webapi-owin/01-authorization)
```
public void Configuration(IAppBuilder app)
{
    var domain = $"https://{ConfigurationManager.AppSettings["Auth0Domain"]}/";
    var apiIdentifier = ConfigurationManager.AppSettings["Auth0ApiIdentifier"];

    var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                Domain.TrimEnd('/') + "/.well-known/openid-configuration",
                new OpenIdConnectConfigurationRetriever());
    app.UseJwtBearerAuthentication(
        new JwtBearerAuthenticationOptions
        {
            AuthenticationMode = AuthenticationMode.Active,
            TokenValidationParameters = new TokenValidationParameters()
            {
                ValidAudience = apiIdentifier,
                ValidIssuer = domain,
                IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) =>
                {
                    var openIdConnectConfig = Task.Run(() => configurationManager.GetConfigurationAsync()).GetAwaiter().GetResult();
                    return openIdConnectConfig.SigningKeys;
                }
            }
        });

    // Configure Web API
    WebApiConfig.Configure(app);
}
```

**Comment by jerriep** [comment]
OWIN 4 support is now available. 

For web applications, the standard OIDC middleware should be used as per the Quickstart:
https://auth0.com/docs/quickstart/webapp/aspnet-owin

For Web API, the package has been updated for OWIN 4. Please refer to Quickstart:
https://auth0.com/docs/quickstart/backend/webapi-owin
