### ISSUE TITLE
Custom claims

### ISSUE THREAD

**Issue by Robar666** [auth0/auth0-aspnet-owin#61]
I created a rule in Auth0 to add custom claims.

```
function (user, context, callback) {
  const namespace = 'https://yada.com/';
  context.idToken[namespace + 'yada_user_id'] = user.app_metadata.YadaUserId;
  callback(null, user, context);
}
```

If I debug during 
```
Provider = new Auth0AuthenticationProvider {
  OnAuthenticated = context => {
    var tokenContainingCustomClaims = context.IdToken;
  }
}
```
and parse the JWT token on https://jwt.io/, I can see the custom claims.

But if I try to access them later via `HttpContext.GetOwinContext().Authentication.User.Claims`, I can only see the default claims, but not my custom claims.

Looking through the [code](https://github.com/auth0/auth0-aspnet-owin/blob/master/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L100) I also couldn't find a LOC which would add custom claims.
Is this a bug in `auth0-aspnet-owin` or do I have to parse the JWT token on my own?

**Comment by jerriep** [comment]
@Robar666 We are actually in the process of deprecating this library and will suggest users move over to using the built-in OWIN OpenID Connect middleware.

Here is a preliminary sample on how to use that particular middleware with Auth0:
https://github.com/auth0/auth0-aspnet-owin/blob/owin4/test/Auth0OwinTest/Startup.cs

**Comment by jerriep** [comment]
Closing this as this library is now deprecated. Users should use the standard OWIN OIDC middleware as per https://github.com/auth0/auth0-aspnet
