### ISSUE TITLE
OWIN 3 alternative

### ISSUE THREAD

**Issue by koolraap** [auth0/auth0-aspnet-owin#65]
I'm not in a position to migrate to OWIN 4. Is there an OWIN 3 alternative? Alternatively is there more information available about the vulnerability that we can use to patch this middleware?

My specific use case is using Auth0 as an external identity provider in Identity Server 3.

**Comment by jerriep** [comment]
@koolraap The vulnerability was described in detail in [this blog post](https://kevinchalet.com/2018/08/08/session-fixation-vulnerability-in-the-auth0-asp-net-and-owin-sdks/)

Auth0 has no intention of patching this library for OWIN 3. You are free to take the [source code](https://github.com/auth0/auth0-aspnet-owin/tree/master/src/Auth0.Owin) nd compile if yourself, however.

**Comment by koolraap** [comment]
Great, that's exactly what I was after. Thank you.

**Comment by koolraap** [comment]
This seems to have done the trick. It's the same way the Facebook/Google/etc providers in Microsoft.Owin 3.1.0 have implemented CSRF/fixation. To watch it in action look for a cookie named `.Aspnet.Correlation.<middlewarename>`.

Note: I'm not a security expert. Caveat emptor. 

Updated Microsoft.Owin from 3.0.1 to 3.1.0
Updated Microsoft.Owin.Security from 3.0.1 to 3.1.0
Updated Microsoft.Owin.Security.Cookies from 3.0.1 to 3.1.0
Updated Microsoft.Owin.Security.Oauth from 3.0.1 to 3.1.0
Updated Microsoft.Owin.Security.StaticFiles from 3.0.1 to 3.1.0

Auth0AuthenticationOptions.cs

Add using

		using Microsoft.Owin.Infrastructure;

Add property

	/// <summary>
        /// Cookie Manager for CSRF
        /// </summary>
        public ICookieManager CookieManager { get; set; }

Add to constructor 		

            // existing line of code (line 40)
            ErrorRedirectPath = new PathString("/");
            CookieManager = new CookieManager();			
		
		
Auth0AuthenticationRepository.cs::AuthenticateCoreAsync

                // existing line of code (line 54)
                properties = Options.StateDataFormat.Unprotect(state);

                // OAuth2 10.12 CSRF
                if (!ValidateCorrelationId(Options.CookieManager, properties, _logger))
                {
                    return new AuthenticationTicket(null, properties);
                }


Auth0AuthenticationRepository.cs::ApplyResponseChallengeAsync

		// existing line of code (196 after previous change)
                AuthenticationProperties properties = challenge.Properties;

                // OAuth2 10.12 CSRF
                GenerateCorrelationId(Options.CookieManager, properties);
